 <article class="product">
    <div class="product-image">
        <img src="{{image}}">
    </div>
    <div class="product-info">
        
            <h1 class="title">{{name}}</h1>
            <h5 class="subtitle">{{compatibility}}</h5>
            <p class="description">
            {{description}}      
            </p>
            <p>
                <span class="price">{{price}} €</span>
                <button class="buy-btn">Buy</button>
            </p>
        
    </div>
</article>